/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 790cf6c360fe65eefed4a77a8e3f6c5c)
interface __BaseEnv_Env {
  AI: Ai;
  TanStackAgent: DurableObjectNamespace<import("./src/server").TanStackAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "TanStackAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
