/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: b2add43a11c791e9a26ce525bfe3e712)
interface __BaseEnv_Env {
  AI: Ai;
  OPENAI_API_KEY: string;
  ANTHROPIC_API_KEY: string;
  ForeverChatAgent: DurableObjectNamespace<
    import("./src/server").ForeverChatAgent
  >;
  INFERENCE_BUFFER: Fetcher /* inference-buffer */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ForeverChatAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "OPENAI_API_KEY" | "ANTHROPIC_API_KEY">
  > {}
}
