/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: b01e07f40234f233cea478e69df27c91)
interface __BaseEnv_Env {
  TaskAgent: DurableObjectNamespace<import("./src/server").TaskAgent>;
  TASK_WORKFLOW: Workflow<
    Parameters<
      import("./src/server").TaskProcessingWorkflow["run"]
    >[0]["payload"]
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "TaskAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
