/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 92fd9c94c4b55cac452665f300505652)
interface __BaseEnv_Env {
  AI: Ai;
  OverseerAgent: DurableObjectNamespace<import("./src/server").OverseerAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "OverseerAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
