/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: fbbddbe41ff7197ce4820371a00c0280)
interface __BaseEnv_Env {
  AI: Ai;
  TELEGRAM_BOT_TOKEN: string;
  TELEGRAM_BOT_USERNAME: string;
  TELEGRAM_WEBHOOK_SECRET_TOKEN: string;
  SupportAgent: DurableObjectNamespace<import("./src/index").SupportAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "SupportAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "TELEGRAM_BOT_TOKEN"
      | "TELEGRAM_BOT_USERNAME"
      | "TELEGRAM_WEBHOOK_SECRET_TOKEN"
    >
  > {}
}
