/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=src/tests/wrangler.jsonc --include-runtime=false src/tests/env.d.ts` (hash: 10a57a164144de7c83cc567113bd2724)
interface __BaseEnv_Env {
  TestHonoAgent: DurableObjectNamespace<import("./worker").TestHonoAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker");
    durableNamespaces: "TestHonoAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
