/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 51cac33c02ec905deb4bd018c1d4d72d)
interface __BaseEnv_Env {
  AI: Ai;
  MyA2A: DurableObjectNamespace<import("./src/server").MyA2A>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MyA2A";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
