/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 66fb28e24108f209979f704747f3d9f5)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  AI: Ai;
  SkillsAgent: DurableObjectNamespace<import("./src/server").SkillsAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "SkillsAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
