/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 809003ae11deb16690c9940552ef2f16)
interface __BaseEnv_Env {
  AI: Ai;
  ReportAgent: DurableObjectNamespace<import("./src/index").ReportAgent>;
  REPORT_WORKFLOW: Workflow<
    Parameters<import("./src/index").ReportWorkflow["run"]>[0]["payload"]
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "ReportAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
