/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: d69d8e3e4bd6d36310b479e7db4b6a1e)
interface __BaseEnv_Env {
  BROWSER: BrowserRun;
  AI: Ai;
  QuickActionsAgent: DurableObjectNamespace<
    import("./src/server").QuickActionsAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "QuickActionsAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
