/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 419c4b3c7994f6ba9bde6379d04dd8cf)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  BROWSER: BrowserRun;
  AI: Ai;
  GitHubLikeMCP: DurableObjectNamespace<import("./src/server").GitHubLikeMCP>;
  Chat: DurableObjectNamespace<import("./src/server").Chat>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "GitHubLikeMCP" | "Chat";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
