/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 0c06e1bdb3a71e73f359569aeec3ab5a)
interface __BaseEnv_Env {
  AI: Ai;
  ANTHROPIC_API_KEY: string;
  DeployChurnAgent: DurableObjectNamespace<
    import("./src/server").DeployChurnAgent
  >;
  DeployChurnSubAgentChild: DurableObjectNamespace<
    import("./src/server").DeployChurnSubAgentChild
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "DeployChurnAgent" | "DeployChurnSubAgentChild";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "ANTHROPIC_API_KEY">
  > {}
}
