import { Agent, callable, routeAgentRequest } from "agents";
import {
  browserExtract,
  browserLinks,
  browserMarkdown,
  browserScreenshot
} from "agents/browser";
import { createQuickActionTools } from "agents/browser/ai";
import { generateText, isStepCount } from "ai";
import { createWorkersAI } from "workers-ai-provider";

// `Env` is the ambient interface generated by `wrangler types` into env.d.ts
// (BROWSER, QuickActionsAgent). Regenerate it with `pnpm run types`.

// Quick Actions are stateless one-shot browser tasks — no session, no sandbox,
// just the BROWSER binding. This agent exposes a few of them as @callable
// methods the UI can invoke directly. (You don't even need an Agent for Quick
// Actions; we use one here so the example matches the SDK's @callable/useAgent
// pattern.)
export class QuickActionsAgent extends Agent<Env> {
  /** Render a page (or raw HTML) to Markdown. */
  @callable()
  async toMarkdown(url: string): Promise<string> {
    return browserMarkdown(this.env.BROWSER, { url });
  }

  /** List every link on a page. */
  @callable()
  async links(url: string): Promise<string[]> {
    return browserLinks(this.env.BROWSER, { url });
  }

  /** Extract structured data from a page with AI, guided by a prompt. */
  @callable()
  async extract(url: string, prompt: string): Promise<unknown> {
    // The default /json model is far more reliable when given a schema as well
    // as a prompt (a prompt alone often returns HTTP 422 "unable to form
    // JSON"), so we pass a simple `items` array schema. See the Browser Run
    // /json docs for richer schemas and bring-your-own-model options.
    return browserExtract<{ items: string[] }>(this.env.BROWSER, {
      url,
      prompt,
      response_format: {
        type: "json_schema",
        schema: {
          type: "object",
          properties: { items: { type: "array", items: { type: "string" } } },
          required: ["items"]
        }
      }
    });
  }

  /** Screenshot a page, returned as a `data:` URL the browser can render. */
  @callable()
  async screenshot(url: string): Promise<string> {
    const shot = await browserScreenshot(this.env.BROWSER, { url });
    const base64 = Buffer.from(shot.data).toString("base64");
    return `data:${shot.contentType};base64,${base64}`;
  }

  /**
   * The same Quick Actions, but exposed to a model as tools so it can decide
   * which to call. `createQuickActionTools` turns the `BROWSER` binding into a
   * `browser_markdown` / `browser_extract` / `browser_links` / `browser_scrape`
   * tool set; the model reads the page and answers on its own.
   */
  @callable()
  async ask(
    url: string,
    question: string
  ): Promise<{ answer: string; toolsUsed: string[] }> {
    const workersai = createWorkersAI({ binding: this.env.AI });
    const tools = createQuickActionTools({ browser: this.env.BROWSER });

    const result = await generateText({
      model: workersai("@cf/moonshotai/kimi-k2.7-code"),
      instructions:
        "You are a research assistant. Use the browser_* tools to read the " +
        "page the user references, then answer concisely. Prefer " +
        "browser_markdown to read a page and browser_extract for structured " +
        "data. Always base your answer on what the tools return.",
      prompt: `Page: ${url}\n\nQuestion: ${question}`,
      tools,
      stopWhen: isStepCount(6)
    });

    const toolsUsed = result.steps.flatMap((step) =>
      step.toolCalls.map((call) => call.toolName)
    );
    return { answer: result.text, toolsUsed: [...new Set(toolsUsed)] };
  }
}

export default {
  async fetch(request: Request, env: Env) {
    return (
      (await routeAgentRequest(request, env)) ||
      new Response("Not found", { status: 404 })
    );
  }
} satisfies ExportedHandler<Env>;
