import { CdpConnection } from "./cdp-connection";

/**
 * A Browser Rendering binding. Structural so it accepts both the classic
 * `Fetcher`-typed binding and the newer `BrowserRun` type generated by
 * `wrangler types` — we only ever use its `fetch` surface.
 */
export interface BrowserBinding {
  fetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response>;
}

/**
 * Browser Run [hostname guardrails](https://developers.cloudflare.com/browser-run/features/guardrails/):
 * restrict which hostnames the session's HTTP/HTTPS requests may reach. Fixed
 * at session launch for every connection to the session, including Live View.
 * Omitted entirely, the platform default applies: all hostnames are allowed.
 * Not supported by Kitesurf.
 */
export interface BrowserSessionGuardrails {
  /**
   * Hostname patterns the browser may request — bare hostnames only (no
   * protocol, port, or path). `*.example.com` matches subdomains; add
   * `example.com` separately to allow the apex.
   */
  allowedDomains?: string[];
  /** Named Cloudflare-maintained domain sets, e.g. `"common-cdns"`. */
  allowedDomainSets?: string[];
}

export interface BrowserTargetInfo {
  id: string;
  type?: string;
  url?: string;
  title?: string;
  description?: string;
  devtoolsFrontendUrl?: string;
  webSocketDebuggerUrl?: string;
}

export interface BrowserSessionInfo {
  sessionId: string;
  targets?: BrowserTargetInfo[];
  webSocketDebuggerUrl?: string;
}

/** {@link connectBrowser} options for the default Chromium engine. */
export interface ConnectChromiumBrowserOptions {
  /** Select the browser engine. Defaults to Chromium. */
  browser?: "chromium";
  timeoutMs?: number;
  keepAliveMs?: number;
  includeTargets?: boolean;
  /**
   * Opt into Browser Run [session recording](https://developers.cloudflare.com/browser-run/features/session-recording/):
   * an rrweb capture of DOM changes, input, and navigation, finalized when the
   * session closes. Set at session-launch time. Retrieve later with
   * {@link getBrowserRecording}.
   */
  recording?: boolean;
}

/**
 * {@link connectBrowser} options for Kitesurf, Cloudflare's connection-scoped,
 * agent-first browser engine. A Kitesurf browser lives and dies with its
 * WebSocket, so the Chromium-only options (`keepAliveMs`, `includeTargets`,
 * `recording`) do not exist on this arm.
 */
export interface ConnectKitesurfBrowserOptions {
  browser: "kitesurf";
  timeoutMs?: number;
}

/**
 * Engine-discriminated {@link connectBrowser} options: selecting
 * `browser: "kitesurf"` removes the Chromium-only options at the type level.
 */
export type ConnectBrowserOptions =
  | ConnectChromiumBrowserOptions
  | ConnectKitesurfBrowserOptions;

/** An rrweb session recording for a closed Browser Run session. */
export interface BrowserRecording {
  sessionId: string;
  /** Recording length in milliseconds. */
  duration: number;
  /**
   * rrweb event arrays keyed by CDP target id (one per tab). Each value can be
   * passed directly to `rrweb-player` to replay that tab.
   */
  events: Record<string, unknown[]>;
}

export class BrowserRenderingError extends Error {
  constructor(
    message: string,
    readonly status: number
  ) {
    super(message);
    this.name = "BrowserRenderingError";
  }
}

/**
 * Whether an error means the platform session is gone: Browser Run uses 404
 * for unknown ids and 410 after `keep_alive` expiry.
 */
export function isMissingBrowserSession(error: unknown): boolean {
  return (
    error instanceof BrowserRenderingError &&
    (error.status === 404 || error.status === 410)
  );
}

function browserSessionEndpoint(
  sessionId?: string,
  options?: {
    keepAliveMs?: number;
    includeTargets?: boolean;
    recording?: boolean;
    browser?: "kitesurf";
  }
): string {
  const path = sessionId
    ? `/v1/devtools/browser/${sessionId}`
    : "/v1/devtools/browser";
  const url = new URL(`https://localhost${path}`);

  if (options?.keepAliveMs !== undefined) {
    url.searchParams.set("keep_alive", String(options.keepAliveMs));
  }
  if (options?.includeTargets) {
    url.searchParams.set("targets", "true");
  }
  if (options?.recording) {
    url.searchParams.set("recording", "true");
  }
  if (options?.browser) {
    url.searchParams.set("browser", options.browser);
  }

  return url.toString();
}

async function parseBrowserSessionInfo(
  response: Response
): Promise<BrowserSessionInfo> {
  const payload = (await response.json()) as {
    sessionId?: unknown;
    targets?: unknown;
    webSocketDebuggerUrl?: unknown;
  };
  const sessionId =
    typeof payload.sessionId === "string" ? payload.sessionId : "";

  if (!sessionId) {
    throw new Error("Browser Rendering response did not include a sessionId");
  }

  return {
    sessionId,
    targets: Array.isArray(payload.targets)
      ? (payload.targets as BrowserTargetInfo[])
      : undefined,
    webSocketDebuggerUrl:
      typeof payload.webSocketDebuggerUrl === "string"
        ? payload.webSocketDebuggerUrl
        : undefined
  };
}

export async function createBrowserSession(
  browser: BrowserBinding,
  options?: {
    keepAliveMs?: number;
    includeTargets?: boolean;
    recording?: boolean;
    guardrails?: BrowserSessionGuardrails;
  }
): Promise<BrowserSessionInfo> {
  // Guardrails ride the acquire request's JSON body (the query string only
  // carries scalar options). The endpoint accepts an empty `{}` body —
  // verified against the live acquire API — so the request shape stays
  // uniform whether or not guardrails are set.
  const response = await browser.fetch(
    browserSessionEndpoint(undefined, options),
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(
        options?.guardrails ? { guardrails: options.guardrails } : {}
      )
    }
  );

  if (!response.ok) {
    throw new BrowserRenderingError(
      `Failed to create Browser Rendering session: ${response.status}`,
      response.status
    );
  }

  return parseBrowserSessionInfo(response);
}

export async function listBrowserTargets(
  browser: BrowserBinding,
  sessionId: string
): Promise<BrowserTargetInfo[]> {
  const response = await browser.fetch(
    `https://localhost/v1/devtools/browser/${sessionId}/json/list`
  );

  if (!response.ok) {
    throw new BrowserRenderingError(
      `Failed to list Browser Rendering targets for ${sessionId}: ${response.status}`,
      response.status
    );
  }

  const payload = (await response.json()) as unknown;
  return Array.isArray(payload) ? (payload as BrowserTargetInfo[]) : [];
}

export async function deleteBrowserSession(
  browser: BrowserBinding,
  sessionId: string
): Promise<void> {
  const response = await browser.fetch(
    `https://localhost/v1/devtools/browser/${sessionId}`,
    { method: "DELETE" }
  );

  if (!response.ok && response.status !== 404) {
    throw new BrowserRenderingError(
      `Failed to delete Browser Rendering session ${sessionId}: ${response.status}`,
      response.status
    );
  }
}

/**
 * Connect to a Browser Rendering session and delete it when closed.
 */
export async function connectBrowser(
  browser: BrowserBinding,
  options?: number | ConnectBrowserOptions
): Promise<CdpConnection> {
  const normalizedOptions: ConnectBrowserOptions =
    typeof options === "number" ? { timeoutMs: options } : (options ?? {});
  if (normalizedOptions.browser === "kitesurf") {
    // The options union already rejects these at the type level for literal
    // call sites; plain-JS callers and spreads can still smuggle them in.
    // Explicitly disabled values are tolerated but never sent — `keep_alive=0`
    // is not a valid Kitesurf query parameter.
    const smuggled = normalizedOptions as {
      keepAliveMs?: number;
      includeTargets?: boolean;
      recording?: boolean;
    };
    if (smuggled.keepAliveMs || smuggled.includeTargets || smuggled.recording) {
      throw new Error(
        "Kitesurf does not support keepAliveMs, includeTargets, or recording"
      );
    }
  }

  const response = await browser.fetch(
    browserSessionEndpoint(
      undefined,
      normalizedOptions.browser === "kitesurf"
        ? { browser: "kitesurf" }
        : {
            keepAliveMs: normalizedOptions.keepAliveMs,
            includeTargets: normalizedOptions.includeTargets,
            recording: normalizedOptions.recording
          }
    ),
    { headers: { Upgrade: "websocket" } }
  );

  const ws = response.webSocket;
  if (!ws) {
    throw new Error(
      "Browser Rendering binding did not return a WebSocket. " +
        "Ensure the 'browser' binding is configured in wrangler.jsonc."
    );
  }

  if (normalizedOptions.browser === "kitesurf") {
    // A Kitesurf browser is scoped to this WebSocket. Browser Run may return
    // an ID for analytics correlation, but it cannot be used with the
    // session-scoped reconnect or delete endpoints.
    ws.accept();
    return new CdpConnection(ws, { timeoutMs: normalizedOptions.timeoutMs });
  }

  const sessionId = response.headers.get("cf-browser-session-id");
  if (!sessionId) {
    throw new Error(
      "Browser Rendering binding did not include a session ID when opening the CDP WebSocket"
    );
  }

  ws.accept();
  return new CdpConnection(ws, {
    timeoutMs: normalizedOptions.timeoutMs,
    onClose: () => {
      deleteBrowserSession(browser, sessionId).catch((error: unknown) => {
        console.warn(
          `[agents/browser] Failed to delete one-shot Browser Run session ${sessionId}`,
          error
        );
      });
    },
    sessionId
  });
}

/**
 * Fetch a Browser Run [session recording](https://developers.cloudflare.com/browser-run/features/session-recording/)
 * by session id, via the Browser Rendering REST API.
 *
 * A recording is only available **after** the session closes (explicit
 * `closeSession()`, idle `keep_alive` expiry, or sweep) and is retained for 30
 * days. Capture the session id while the session is alive — e.g. from
 * `connector.liveView()`/`sessionInfo()` — then call this once it has ended.
 *
 * Unlike the binding-based helpers, this hits `api.cloudflare.com` directly, so
 * it needs an account id and an API token with `Browser Rendering` read access
 * (the Workers Browser Run binding cannot read recordings).
 */
export async function getBrowserRecording(options: {
  accountId: string;
  apiToken: string;
  sessionId: string;
  /** Override for testing; defaults to the global `fetch`. */
  fetchImpl?: typeof fetch;
}): Promise<BrowserRecording> {
  const { accountId, apiToken, sessionId } = options;
  const fetchImpl = options.fetchImpl ?? fetch;
  const endpoint = `https://api.cloudflare.com/client/v4/accounts/${accountId}/browser-rendering/recording/${sessionId}`;

  const response = await fetchImpl(endpoint, {
    headers: { Authorization: `Bearer ${apiToken}` }
  });

  if (!response.ok) {
    throw new BrowserRenderingError(
      `Failed to fetch Browser Run recording for ${sessionId}: ${response.status}`,
      response.status
    );
  }

  // The recording endpoint returns the recording object directly; tolerate a
  // standard v4 `{ result }` envelope in case that changes.
  const payload = (await response.json()) as
    | BrowserRecording
    | { result?: BrowserRecording };
  const recording =
    "result" in payload && payload.result ? payload.result : payload;

  return recording as BrowserRecording;
}

export interface ConnectBrowserSessionOptions {
  timeoutMs?: number;
  /**
   * Invoked once when the returned {@link CdpConnection} reaches a terminal
   * state — an explicit `close()`, peer closure, or a socket error. The
   * session itself is never deleted on close — pass an `onClose` that
   * deletes it for one-shot (create-and-close) semantics.
   */
  onClose?: () => void;
  /**
   * Invoked on every CDP command sent over the returned {@link CdpConnection} —
   * an activity signal for idle tracking. Keep it cheap and synchronous;
   * throttle any I/O it triggers.
   */
  onActivity?: () => void;
}

/**
 * Connect to an existing Browser Rendering session without deleting it on close.
 */
export async function connectBrowserSession(
  browser: BrowserBinding,
  sessionId: string,
  options?: ConnectBrowserSessionOptions
): Promise<CdpConnection>;
/**
 * @deprecated Pass `{ timeoutMs }` instead of a bare number — the numeric
 * form will be removed.
 */
export async function connectBrowserSession(
  browser: BrowserBinding,
  sessionId: string,
  timeoutMs?: number
): Promise<CdpConnection>;
export async function connectBrowserSession(
  browser: BrowserBinding,
  sessionId: string,
  options?: number | ConnectBrowserSessionOptions
): Promise<CdpConnection> {
  const normalized =
    typeof options === "number" ? { timeoutMs: options } : (options ?? {});
  const response = await browser.fetch(browserSessionEndpoint(sessionId), {
    headers: { Upgrade: "websocket" }
  });

  const ws = response.webSocket;
  if (!ws) {
    // Carry the upgrade status: a 404/410 here means the browser expired
    // after the caller last saw it alive (see isMissingBrowserSession).
    throw new BrowserRenderingError(
      `Browser Rendering binding did not return a WebSocket for session ${sessionId} (${response.status})`,
      response.status
    );
  }

  ws.accept();
  return new CdpConnection(ws, {
    timeoutMs: normalized.timeoutMs,
    onClose: normalized.onClose,
    sessionId,
    onActivity: normalized.onActivity
  });
}

/** One-shot session options for the default Chromium engine. */
export interface OneShotChromiumSessionOptions {
  /** Select the browser engine. Defaults to Chromium. */
  browser?: "chromium";
  timeoutMs?: number;
  /** Platform `keep_alive` in milliseconds. */
  keepAliveMs?: number;
  /** Opt into Browser Run session recording (rrweb capture). */
  recording?: boolean;
  /** Hostname guardrails, fixed at launch. */
  guardrails?: BrowserSessionGuardrails;
}

/**
 * One-shot session options for Kitesurf. The Chromium-only options —
 * `guardrails`, `keepAliveMs`, `recording` — do not exist on this arm:
 * Kitesurf does not support them.
 */
export interface OneShotKitesurfSessionOptions {
  browser: "kitesurf";
  timeoutMs?: number;
}

/**
 * Engine-discriminated {@link openOneShotBrowserSession} options: selecting
 * `browser: "kitesurf"` removes the Chromium-only options at the type level.
 */
export type OneShotBrowserSessionOptions =
  | OneShotChromiumSessionOptions
  | OneShotKitesurfSessionOptions;

/**
 * Open a one-shot browser session: create, connect, and delete the platform
 * session when the returned {@link CdpConnection} closes. No store involved —
 * one-shot sessions have no name and no durability.
 */
export async function openOneShotBrowserSession(
  browser: BrowserBinding,
  options: OneShotBrowserSessionOptions = {}
): Promise<CdpConnection> {
  if (options.browser === "kitesurf") {
    // The options union already rejects these at the type level for literal
    // call sites; plain-JS callers and spreads can still smuggle them in, so
    // fail loudly in one place with one message.
    const smuggled = options as {
      guardrails?: unknown;
      keepAliveMs?: unknown;
      recording?: unknown;
    };
    if (smuggled.guardrails || smuggled.keepAliveMs || smuggled.recording) {
      throw new Error(
        "Kitesurf does not support guardrails, keepAliveMs, or recording"
      );
    }
    // Kitesurf browsers are scoped to their WebSocket — connectBrowser is
    // already one-shot there.
    return connectBrowser(browser, {
      browser: "kitesurf",
      timeoutMs: options.timeoutMs
    });
  }

  const info = await createBrowserSession(browser, {
    keepAliveMs: options.keepAliveMs,
    recording: options.recording,
    guardrails: options.guardrails
  });
  try {
    return await connectBrowserSession(browser, info.sessionId, {
      timeoutMs: options.timeoutMs,
      onClose: () => {
        deleteBrowserSession(browser, info.sessionId).catch(
          (error: unknown) => {
            console.warn(
              `[agents/browser] Failed to delete one-shot Browser Run session ${info.sessionId}`,
              error
            );
          }
        );
      }
    });
  } catch (error) {
    // The session was allocated but never got its delete-on-close owner —
    // reclaim it now instead of leaving it to expire.
    try {
      await deleteBrowserSession(browser, info.sessionId);
    } catch {
      // Best-effort: keep_alive expiry reclaims it.
    }
    throw error;
  }
}
