// Generated by running `wrangler types env.d.ts --include-runtime false`.
// Re-run `npm run types` after changing Wrangler bindings.
declare namespace Cloudflare {
  interface Env {
    AI: Ai;
  }
}
interface Env extends Cloudflare.Env {}
