/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: cf722057a6393773c412d8176dfc1f80)
interface __BaseEnv_Env {
  AI: Ai;
  ResumableStreamingChat: DurableObjectNamespace<
    import("./src/server").ResumableStreamingChat
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ResumableStreamingChat";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
