/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: c59e0071a1d32d456f8079794cc150ab)
interface __BaseEnv_Env {
  EMAIL: SendEmail;
  EMAIL_FROM: "mailbox-7f3a@example.com";
  EmailServiceAgent: DurableObjectNamespace<
    import("./src/server").EmailServiceAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "EmailServiceAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "EMAIL_FROM">
  > {}
}
