/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: b059b87484f4364dd5dbaafdc32c57bd)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  BROWSER: BrowserRun;
  AI: Ai;
  DEV_USER: "";
  AssistantDirectory: DurableObjectNamespace<
    import("./src/server").AssistantDirectory
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "AssistantDirectory";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "DEV_USER">
  > {}
}
