// Generated by `think types`. Do not edit this file directly.
// Re-run `think types` after changing Think agents or Wrangler bindings.
// <think-generated>
declare module "virtual:think/entry" {
  const entry: ExportedHandler<Cloudflare.Env>;
  export default entry;
  export const ThinkAgent_Assistant: (typeof import("./agents/assistant/agent"))["AssistantDirectory"];
  export const ThinkSubAgent_Assistant_MyAssistant: (typeof import("./agents/assistant/agents/my-assistant/agent"))["MyAssistant"];
}
declare module "virtual:think/router" {
  export const thinkRouter: import("@cloudflare/think/server-entry").ThinkRouter;
}

declare namespace Cloudflare {
  interface Env {
    AssistantDirectory: DurableObjectNamespace<
      InstanceType<(typeof import("./agents/assistant/agent"))["AssistantDirectory"]>
    >;
  }
}
// </think-generated>
