/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 53bbd72b1c6572d86e56d2e6e02c259b)
interface __BaseEnv_Env {
  DoAgent: DurableObjectNamespace<import("./src/index").DoAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "DoAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
