/**
 * Bundle the harness daemon (src/harness/container/runtime/main.ts) into
 * one Node ES module and embed it as a string, so `ContainerHarness` can
 * install it into a stock `cloudflare/debian-trixie` container: no image to
 * build, no package to install in the container.
 *
 * Writes src/harness/container/daemon-source.generated.ts (not committed).
 * Run by scripts/build.ts before the package build; run it directly after
 * changing the runtime to test without a full build.
 */
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { build } from "esbuild";

const OUT = "src/harness/container/daemon-source.generated.ts";

export async function buildDaemon(): Promise<void> {
  const result = await build({
    entryPoints: ["src/harness/container/runtime/main.ts"],
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node22",
    minify: true,
    write: false,
    legalComments: "none"
  });
  const source = result.outputFiles[0]?.text;
  if (!source) throw new Error("The daemon bundle is empty");
  const version = createHash("sha256")
    .update(source)
    .digest("hex")
    .slice(0, 16);
  writeFileSync(
    OUT,
    [
      "// Generated by scripts/build-daemon.ts. Do not edit.",
      "",
      "/** The harness daemon, bundled: one Node ES module. */",
      `export const DAEMON_SOURCE: string = ${JSON.stringify(source)};`,
      "",
      "/** A hash of `DAEMON_SOURCE`, to tell daemon builds apart. */",
      `export const DAEMON_VERSION = ${JSON.stringify(version)};`,
      ""
    ].join("\n")
  );
  console.log(`daemon: ${(source.length / 1024).toFixed(0)} KiB, ${version}`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  await buildDaemon();
}
