/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 0ac768a90f264c431ad8c52044c6cb6b)
interface __BaseEnv_Env {
  AI: Ai;
  VoiceInputAgent: DurableObjectNamespace<
    import("./src/server").VoiceInputAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "VoiceInputAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
