/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 4bfff30f87e43cb016c0ca04fedb43e6)
interface __BaseEnv_Env {
  MyMCP: DurableObjectNamespace<import("./src/server").MyMCP>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MyMCP";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
