/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 3d5f4faffba2a9fc5dba5afae402ff12)
interface __BaseEnv_Env {
  McpClientObject: DurableObjectNamespace<
    import("./src/server").McpClientObject
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "McpClientObject";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
