/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 4456aa4f73f2709dc5f79ee45a28bb31)
interface __BaseEnv_Env {
  AI: Ai;
  BrowserCodemode: DurableObjectNamespace<
    import("./src/server").BrowserCodemode
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "BrowserCodemode";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
