/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 5e0b62c3b1d9a63f9194f8307b8dad2f)
interface __BaseEnv_Env {
  AI: Ai;
  GatekeeperAgent: DurableObjectNamespace<
    import("./src/server").GatekeeperAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "GatekeeperAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
