/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 3a407cdef95103f8a24b6969cbedaafd)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  AI: Ai;
  WorkspaceChatAgent: DurableObjectNamespace<
    import("./src/server").WorkspaceChatAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "WorkspaceChatAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
