/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 3bf628efb99539c88ee3cabc34108cde)
interface __BaseEnv_Env {
  AI: Ai;
  CoordinatorAgent: DurableObjectNamespace<
    import("./src/server").CoordinatorAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "CoordinatorAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
