/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 52bfdabcb7e4933e66260fa5f1d0bd6b)
interface __BaseEnv_Env {}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
