/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 5701b263692b6a58440caa86e4480d4a)
interface __BaseEnv_Env {
  AI: Ai;
  MyVoiceAgent: DurableObjectNamespace<import("./src/index").MyVoiceAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "MyVoiceAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
