/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: e8d7ffe1a6ecd86a3fd6f8de13f46c5c)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  AI: Ai;
  SELF_MODIFYING_HARNESS: DurableObjectNamespace<
    import("./src/server").SelfModifyingHarnessObject
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "SelfModifyingHarnessObject";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
