/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 7a817de175737564c0050d998d48cc5b)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  AI: Ai;
  EMAIL_SECRET: string;
  StateAgent: DurableObjectNamespace<import("./src/server").StateAgent>;
  CallableAgent: DurableObjectNamespace<import("./src/server").CallableAgent>;
  StreamingAgent: DurableObjectNamespace<import("./src/server").StreamingAgent>;
  ScheduleAgent: DurableObjectNamespace<import("./src/server").ScheduleAgent>;
  SqlAgent: DurableObjectNamespace<import("./src/server").SqlAgent>;
  ConnectionsAgent: DurableObjectNamespace<
    import("./src/server").ConnectionsAgent
  >;
  RoutingAgent: DurableObjectNamespace<import("./src/server").RoutingAgent>;
  ReadonlyAgent: DurableObjectNamespace<import("./src/server").ReadonlyAgent>;
  RetryAgent: DurableObjectNamespace<import("./src/server").RetryAgent>;
  DurableExecutionAgent: DurableObjectNamespace<
    import("./src/server").DurableExecutionAgent
  >;
  ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
  ToolsAgent: DurableObjectNamespace<import("./src/server").ToolsAgent>;
  CodemodeAgent: DurableObjectNamespace<import("./src/server").CodemodeAgent>;
  SupervisorAgent: DurableObjectNamespace<
    import("./src/server").SupervisorAgent
  >;
  ChildAgent: DurableObjectNamespace<import("./src/server").ChildAgent>;
  LobbyAgent: DurableObjectNamespace<import("./src/server").LobbyAgent>;
  RoomAgent: DurableObjectNamespace<import("./src/server").RoomAgent>;
  ManagerAgent: DurableObjectNamespace<import("./src/server").ManagerAgent>;
  FanoutWorkerAgent: DurableObjectNamespace<
    import("./src/server").FanoutWorkerAgent
  >;
  PipelineOrchestratorAgent: DurableObjectNamespace<
    import("./src/server").PipelineOrchestratorAgent
  >;
  ValidatorStageAgent: DurableObjectNamespace<
    import("./src/server").ValidatorStageAgent
  >;
  TransformStageAgent: DurableObjectNamespace<
    import("./src/server").TransformStageAgent
  >;
  EnrichStageAgent: DurableObjectNamespace<
    import("./src/server").EnrichStageAgent
  >;
  PlaygroundMcpServer: DurableObjectNamespace<
    import("./src/server").PlaygroundMcpServer
  >;
  McpClientAgent: DurableObjectNamespace<import("./src/server").McpClientAgent>;
  BasicWorkflowAgent: DurableObjectNamespace<
    import("./src/server").BasicWorkflowAgent
  >;
  ApprovalAgent: DurableObjectNamespace<import("./src/server").ApprovalAgent>;
  ReceiveEmailAgent: DurableObjectNamespace<
    import("./src/server").ReceiveEmailAgent
  >;
  SecureEmailAgent: DurableObjectNamespace<
    import("./src/server").SecureEmailAgent
  >;
  PlaygroundVoiceAgent: DurableObjectNamespace<
    import("./src/server").PlaygroundVoiceAgent
  >;
  ProcessingWorkflow: Workflow<
    Parameters<import("./src/server").ProcessingWorkflow["run"]>[0]["payload"]
  >;
  ApprovalWorkflow: Workflow<
    Parameters<import("./src/server").ApprovalWorkflow["run"]>[0]["payload"]
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces:
      | "StateAgent"
      | "CallableAgent"
      | "StreamingAgent"
      | "ScheduleAgent"
      | "SqlAgent"
      | "ConnectionsAgent"
      | "RoutingAgent"
      | "ReadonlyAgent"
      | "RetryAgent"
      | "DurableExecutionAgent"
      | "ChatAgent"
      | "ToolsAgent"
      | "CodemodeAgent"
      | "SupervisorAgent"
      | "ChildAgent"
      | "LobbyAgent"
      | "RoomAgent"
      | "ManagerAgent"
      | "FanoutWorkerAgent"
      | "PipelineOrchestratorAgent"
      | "ValidatorStageAgent"
      | "TransformStageAgent"
      | "EnrichStageAgent"
      | "PlaygroundMcpServer"
      | "McpClientAgent"
      | "BasicWorkflowAgent"
      | "ApprovalAgent"
      | "ReceiveEmailAgent"
      | "SecureEmailAgent"
      | "PlaygroundVoiceAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "EMAIL_SECRET">
  > {}
}
