/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 9b5915b31b6e7089c0d40a20b40ea7e3)
interface __BaseEnv_Env {
  AI: Ai;
  GATEWAY: "demo-gateway";
  MODEL: "openai/gpt-5.4";
  GatewayResumeAgent: DurableObjectNamespace<
    import("./src/server").GatewayResumeAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "GatewayResumeAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "GATEWAY" | "MODEL">
  > {}
}
