/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts`
interface __BaseEnv_Env {
  Supervisor: DurableObjectNamespace<import("./src/index").Supervisor>;
  LOADER: WorkerLoader;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "Supervisor";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
