/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 24b809d653c1b74071234b491f4604fe)
interface __BaseEnv_Env {
  AI: Ai;
  MyVoiceAgent: DurableObjectNamespace<import("./src/server").MyVoiceAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MyVoiceAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
