/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 6231409333b2bf74055dbea694270ab0)
interface __BaseEnv_Env {
  LegacyElicitationAgent: DurableObjectNamespace<
    import("./src/index").LegacyElicitationAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "LegacyElicitationAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
