/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: fc61aaf892d164e20817f5d22aa2f88b)
interface __BaseEnv_Env {
  PayMCP: DurableObjectNamespace<import("./src/server").PayMCP>;
  PAY_AGENT: DurableObjectNamespace<import("./src/server").PayAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "PayMCP" | "PayAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
