/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false env.d.ts` (hash: 9c3627f289bf2e87ec7301785d9bd800)
interface __BaseEnv_Env {
  AI: Ai;
  MyAgent: DurableObjectNamespace<import("./src/server").MyAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MyAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
