/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 76c5f72967e59df334c7e9f69d3d7d19)
interface __BaseEnv_Env {
  AI: Ai;
  OpenCodeAgent: DurableObjectNamespace<import("./src/server").OpenCodeAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "OpenCodeAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
