/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 7b78586ac179173004a18f9169784f7d)
interface __BaseEnv_Env {
  AI: Ai;
  MyMCP: DurableObjectNamespace<import("./src/server").MyMCP>;
  Chat: DurableObjectNamespace<import("./src/server").Chat>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MyMCP" | "Chat";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
