/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 93f43da6bb77d081a6a0bf453435a5da)
interface __BaseEnv_Env {
  AI: Ai;
  DynamicToolsAgent: DurableObjectNamespace<
    import("./src/server").DynamicToolsAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "DynamicToolsAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
