/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 83849e094f846b2a30145fb06af64f25)
interface __BaseEnv_Env {
  AI: Ai;
  AiSdkAgent: DurableObjectNamespace<import("./src/server").AiSdkAgent>;
  PiAgent: DurableObjectNamespace<import("./src/server").PiAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "AiSdkAgent" | "PiAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
