/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false env.d.ts` (hash: 3a88022d8b6a942a82baf07e652acff9)
interface __BaseEnv_Env {
  MyAgent: DurableObjectNamespace<import("./src/server").MyAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MyAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
