/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 7e46a4b034a3ec92f0729f5d8ebbb00c)
interface __BaseEnv_Env {
  AI_GATEWAY_URL: "https://gateway.ai.cloudflare.com/v1/<account>/<gateway>";
  AI_GATEWAY_TOKEN: string;
  ClaudeCodeAgent: DurableObjectNamespace<
    import("./src/index").ClaudeCodeAgent
  >;
  CodexAgent: DurableObjectNamespace<import("./src/index").CodexAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "ClaudeCodeAgent" | "CodexAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "AI_GATEWAY_URL" | "AI_GATEWAY_TOKEN">
  > {}
}
