/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: ee18ee3ca49c797c2cbfb58171181234)
interface __BaseEnv_Env {
  AI: Ai;
  WORKSPACE: R2Bucket;
  Coder: DurableObjectNamespace<import("./src/server").Coder>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Coder";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
