/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: e6ae39b79765d1cb11d1be9c209227ef)
interface __BaseEnv_Env {
  AI: Ai;
  HumanInTheLoop: DurableObjectNamespace<import("./src/server").HumanInTheLoop>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "HumanInTheLoop";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
