/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 31a6fe3a80f6ce5b56985da1477f1954)
interface __BaseEnv_Env {
  ASSETS: Fetcher;
  CHESS: DurableObjectNamespace<import("./src/index").ChessGame>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "ChessGame";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
