/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 0cb7d4d3f8bfd65f4a85db3f24bf892b)
interface __BaseEnv_Env {
  AI: Ai;
  ThinkAgent: DurableObjectNamespace<import("./src/server").ThinkAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ThinkAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
