/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: d71a45ddedaf82ce81e8f10f90271411)
interface __BaseEnv_Env {
  ProbeAgent: DurableObjectNamespace<import("./src/server").ProbeAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ProbeAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
