/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 602cfc788a2c039adc7bc400385cba5c)
interface __BaseEnv_Env {
  AI: Ai;
  OpsApprovalAgent: DurableObjectNamespace<
    import("./src/server").OpsApprovalAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "OpsApprovalAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
