/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 44f9ea020d93b0b286a8c2a9a42a075e)
interface __BaseEnv_Env {
  AI: Ai;
  Assistant: DurableObjectNamespace<import("./src/server").Assistant>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Assistant";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
