/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: d46c67171be48023f3aa5f25e4b6d750)
interface __BaseEnv_Env {
  AI: Ai;
  StructuredInputAgent: DurableObjectNamespace<
    import("./src/server").StructuredInputAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "StructuredInputAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
