/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: abda0ee0b862e4c9c939f0e2d6c096b7)
interface __BaseEnv_Env {
  AI: Ai;
  Inbox: DurableObjectNamespace<import("./src/server").Inbox>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Inbox";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
