/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 257a3aec1f19c0e70426882a4242a7d5)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  BROWSER: BrowserRun;
  AI: Ai;
  LiveViewAgent: DurableObjectNamespace<import("./src/server").LiveViewAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "LiveViewAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
