/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 80d057f00bf6967c0ff4e2e20c6f1a38)
interface __BaseEnv_Env {
  PAY_AGENT: DurableObjectNamespace<import("./src/server").PayAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "PayAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
