/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: b6c34a483a55cc73f15613f9e672d55a)
interface __BaseEnv_Env {
  AI: Ai;
  INFERENCE_BUFFER: DurableObjectNamespace<
    import("./src/index").InferenceBuffer
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "InferenceBuffer";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
