/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 1106b8a69e91c250bb1ceb72470edda9)
interface __BaseEnv_Env {
  AI: Ai;
  GATEWAY_ID: "default";
  CodingOrchestrator: DurableObjectNamespace<
    import("./src/server").CodingOrchestrator
  >;
  Sandbox: DurableObjectNamespace<import("./src/server").Sandbox>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "CodingOrchestrator" | "Sandbox";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "GATEWAY_ID">
  > {}
}
