/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 1ca941486ec665e35b6aff23a85e2076)
interface __BaseEnv_Env {
  SessionObject: DurableObjectNamespace<import("./src/index").SessionObject>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "SessionObject";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
