/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: b2f62f09f0b59317f29b79fe36b1e880)
interface __BaseEnv_Env {
  AI: Ai;
  ContextOverflowAgent: DurableObjectNamespace<
    import("./src/server").ContextOverflowAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ContextOverflowAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
