import type {
  TTSProvider,
  StreamingTTSProvider,
  Transcriber,
  TranscriberSession,
  TranscriberSessionOptions
} from "@cloudflare/voice";

const DEFAULT_STT_MODEL_ID = "scribe_v2_realtime";
const DEFAULT_STT_AUDIO_FORMAT = "pcm_16000";
const DEFAULT_STT_SAMPLE_RATE = 16_000;
const DEFAULT_STT_BASE_URL =
  "wss://api.elevenlabs.io/v1/speech-to-text/realtime";
// About 30 seconds of 16 kHz mono PCM16 audio while the socket connects.
const MAX_PENDING_BYTES = 960_000;

export interface ElevenLabsTTSOptions {
  /** ElevenLabs API key. */
  apiKey: string;
  /** Voice ID. Browse voices at https://elevenlabs.io/app/voice-library @default "JBFqnCBsd6RMkjVDRZzb" (George) */
  voiceId?: string;
  /** Model ID. @default "eleven_flash_v2_5" (lowest latency) */
  modelId?: string;
  /** Output format. @default "mp3_44100_128" */
  outputFormat?: string;
}

export interface ElevenLabsSTTOptions {
  /** ElevenLabs API key. */
  apiKey: string;
  /** Realtime STT model ID. @default "scribe_v2_realtime" */
  modelId?: string;
  /** Audio format sent by the voice pipeline. @default "pcm_16000" */
  audioFormat?: string;
  /** Sample rate in Hz. @default 16000 */
  sampleRate?: number;
  /** Optional language code, e.g. "en" or "eng". */
  languageCode?: string;
  /** Bias recognition toward these terms. Realtime supports up to 50 terms. */
  keyterms?: string[];
  /** Remove filler words, false starts, and disfluencies. @default false */
  noVerbatim?: boolean;
  /** Filter background audio before transcription. @default false */
  filterBackgroundAudio?: boolean;
  /** Include language detection metadata on committed transcripts. @default false */
  includeLanguageDetection?: boolean;
  /** Disable provider-side logging where supported. @default true */
  enableLogging?: boolean;
  /** Silence threshold used by ElevenLabs VAD commit strategy. @default 1.5 */
  vadSilenceThresholdSecs?: number;
  /** VAD confidence threshold. @default 0.4 */
  vadThreshold?: number;
  /** Minimum speech duration in milliseconds. @default 100 */
  minSpeechDurationMs?: number;
  /** Minimum silence duration in milliseconds. @default 100 */
  minSilenceDurationMs?: number;
  /** Override the realtime WebSocket URL. */
  baseUrl?: string;
}

const DEFAULT_VOICE_ID = "JBFqnCBsd6RMkjVDRZzb"; // George
const DEFAULT_MODEL_ID = "eleven_flash_v2_5";
const DEFAULT_OUTPUT_FORMAT = "mp3_44100_128";

/**
 * ElevenLabs text-to-speech provider for the Agents voice pipeline.
 *
 * Implements both `TTSProvider` and `StreamingTTSProvider` from `agents/voice`.
 *
 * - `synthesize(text)` — waits for the full audio response (simple, higher latency).
 * - `synthesizeStream(text)` — uses the ElevenLabs `/stream` endpoint, yielding audio
 *   chunks as they are generated (lower time-to-first-audio per sentence).
 *
 * Set as the `tts` provider on your VoiceAgent subclass:
 *
 * @example
 * ```typescript
 * import { Agent } from "agents";
 * import { withVoice } from "@cloudflare/voice";
 * import { ElevenLabsTTS } from "@cloudflare/voice-elevenlabs";
 *
 * const VoiceAgent = withVoice(Agent);
 *
 * export class MyAgent extends VoiceAgent<Env> {
 *   tts = new ElevenLabsTTS({ apiKey: this.env.ELEVENLABS_API_KEY });
 *
 *   async onTurn(transcript, context) { ... }
 * }
 * ```
 */
export class ElevenLabsTTS implements TTSProvider, StreamingTTSProvider {
  #apiKey: string;
  #voiceId: string;
  #modelId: string;
  #outputFormat: string;

  constructor(options: ElevenLabsTTSOptions) {
    this.#apiKey = options.apiKey;
    this.#voiceId = options.voiceId ?? DEFAULT_VOICE_ID;
    this.#modelId = options.modelId ?? DEFAULT_MODEL_ID;
    this.#outputFormat = options.outputFormat ?? DEFAULT_OUTPUT_FORMAT;
  }

  /**
   * Non-streaming TTS — sends the full text and waits for the complete
   * audio response. Simple but higher latency per sentence.
   */
  async synthesize(
    text: string,
    signal?: AbortSignal
  ): Promise<ArrayBuffer | null> {
    try {
      const response = await fetch(
        `https://api.elevenlabs.io/v1/text-to-speech/${this.#voiceId}?output_format=${this.#outputFormat}`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "xi-api-key": this.#apiKey
          },
          body: JSON.stringify({
            text,
            model_id: this.#modelId
          }),
          signal
        }
      );

      if (!response.ok) {
        console.error(
          `[ElevenLabsTTS] Error: ${response.status} ${response.statusText}`
        );
        return null;
      }

      return await response.arrayBuffer();
    } catch (error) {
      console.error("[ElevenLabsTTS] Error:", error);
      return null;
    }
  }

  /**
   * Streaming TTS — sends the full text and yields audio chunks as they
   * are generated by ElevenLabs. Uses the `/stream` endpoint which returns
   * a chunked HTTP response.
   *
   * This reduces time-to-first-audio within each sentence: the client
   * starts playing audio before the full sentence has been synthesized.
   */
  async *synthesizeStream(
    text: string,
    signal?: AbortSignal
  ): AsyncGenerator<ArrayBuffer> {
    try {
      const response = await fetch(
        `https://api.elevenlabs.io/v1/text-to-speech/${this.#voiceId}/stream?output_format=${this.#outputFormat}`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "xi-api-key": this.#apiKey
          },
          body: JSON.stringify({
            text,
            model_id: this.#modelId
          }),
          signal
        }
      );

      if (!response.ok || !response.body) {
        console.error(
          `[ElevenLabsTTS] Stream error: ${response.status} ${response.statusText}`
        );
        return;
      }

      const reader = response.body.getReader();
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        if (value && value.byteLength > 0) {
          // value is a Uint8Array — yield the underlying ArrayBuffer slice
          yield value.buffer.slice(
            value.byteOffset,
            value.byteOffset + value.byteLength
          );
        }
      }
    } catch (error) {
      console.error("[ElevenLabsTTS] Stream error:", error);
    }
  }
}

/**
 * ElevenLabs Scribe v2 Realtime speech-to-text provider for the Agents voice
 * pipeline. Uses ElevenLabs' VAD commit strategy so committed transcript
 * segments map to voice-agent turns.
 */
export class ElevenLabsSTT implements Transcriber {
  #options: ElevenLabsSTTOptions;

  constructor(options: ElevenLabsSTTOptions) {
    this.#options = options;
  }

  createSession(options?: TranscriberSessionOptions): TranscriberSession {
    return new ElevenLabsSTTSession(this.#options, options);
  }
}

class ElevenLabsSTTSession implements TranscriberSession {
  #providerOptions: ElevenLabsSTTOptions;
  #sessionOptions: TranscriberSessionOptions | undefined;
  #ws: WebSocket | null = null;
  #closed = false;
  #ready: Promise<void>;
  #readyResolve!: () => void;
  #readyReject!: (error: Error) => void;
  #readySettled = false;
  #pendingChunks: ArrayBuffer[] = [];
  #pendingBytes = 0;
  #pendingOverflowLogged = false;
  #speechStarted = false;

  constructor(
    providerOptions: ElevenLabsSTTOptions,
    sessionOptions?: TranscriberSessionOptions
  ) {
    this.#providerOptions = providerOptions;
    this.#sessionOptions = sessionOptions;
    this.#ready = new Promise((resolve, reject) => {
      this.#readyResolve = resolve;
      this.#readyReject = reject;
    });
    this.#ready.catch(() => {});
    void this.#connect();
  }

  waitUntilReady(): Promise<void> {
    return this.#ready;
  }

  feed(chunk: ArrayBuffer): void {
    if (this.#closed) return;
    if (!this.#ws) {
      if (this.#pendingBytes + chunk.byteLength > MAX_PENDING_BYTES) {
        if (!this.#pendingOverflowLogged) {
          this.#pendingOverflowLogged = true;
          console.error(
            "[ElevenLabsSTT] Pending audio buffer full — dropping audio until the socket connects."
          );
        }
        return;
      }
      this.#pendingBytes += chunk.byteLength;
      this.#pendingChunks.push(chunk);
      return;
    }
    this.#sendAudioChunk(chunk);
  }

  close(): void {
    if (this.#closed) return;
    this.#closed = true;
    this.#rejectReady(
      new Error("ElevenLabsSTT: WebSocket closed before session start.")
    );
    this.#pendingChunks = [];
    this.#pendingBytes = 0;
    this.#ws?.close();
    this.#ws = null;
  }

  async #connect(): Promise<void> {
    try {
      const response = await fetch(this.#connectionUrl(), {
        headers: {
          Upgrade: "websocket",
          "xi-api-key": this.#providerOptions.apiKey
        }
      });

      const ws = (response as unknown as { webSocket?: WebSocket }).webSocket;
      if (!ws) {
        throw new Error(
          `ElevenLabsSTT: failed to establish WebSocket connection (HTTP ${response.status}).`
        );
      }

      ws.addEventListener("message", (event: MessageEvent) => {
        this.#handleMessage(event);
      });
      ws.addEventListener("error", () => {
        this.#rejectReady(new Error("ElevenLabsSTT: WebSocket error."));
        this.#closed = true;
      });
      ws.addEventListener("close", () => {
        this.#rejectReady(
          new Error("ElevenLabsSTT: WebSocket closed before session start.")
        );
        this.#closed = true;
      });

      (ws as unknown as { accept: () => void }).accept();

      if (this.#closed) {
        ws.close();
        return;
      }

      this.#ws = ws;
      for (const chunk of this.#pendingChunks) {
        this.#sendAudioChunk(chunk);
      }
      this.#pendingChunks = [];
      this.#pendingBytes = 0;
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      this.#rejectReady(new Error(message));
      this.#closed = true;
    }
  }

  #resolveReady(): void {
    if (this.#readySettled) return;
    this.#readySettled = true;
    this.#readyResolve();
  }

  #rejectReady(error: Error): void {
    if (this.#readySettled) return;
    this.#readySettled = true;
    this.#readyReject(error);
  }

  #connectionUrl(): string {
    const url = new URL(
      (this.#providerOptions.baseUrl ?? DEFAULT_STT_BASE_URL)
        .replace(/^wss:\/\//, "https://")
        .replace(/^ws:\/\//, "http://")
    );
    url.searchParams.set(
      "model_id",
      this.#providerOptions.modelId ?? DEFAULT_STT_MODEL_ID
    );
    url.searchParams.set(
      "audio_format",
      this.#providerOptions.audioFormat ?? DEFAULT_STT_AUDIO_FORMAT
    );
    url.searchParams.set("commit_strategy", "vad");
    url.searchParams.set(
      "vad_silence_threshold_secs",
      String(this.#providerOptions.vadSilenceThresholdSecs ?? 1.5)
    );
    url.searchParams.set(
      "vad_threshold",
      String(this.#providerOptions.vadThreshold ?? 0.4)
    );
    url.searchParams.set(
      "min_speech_duration_ms",
      String(this.#providerOptions.minSpeechDurationMs ?? 100)
    );
    url.searchParams.set(
      "min_silence_duration_ms",
      String(this.#providerOptions.minSilenceDurationMs ?? 100)
    );
    if (this.#providerOptions.languageCode) {
      url.searchParams.set("language_code", this.#providerOptions.languageCode);
    }
    if (this.#providerOptions.noVerbatim !== undefined) {
      url.searchParams.set(
        "no_verbatim",
        String(this.#providerOptions.noVerbatim)
      );
    }
    if (this.#providerOptions.filterBackgroundAudio !== undefined) {
      url.searchParams.set(
        "filter_background_audio",
        String(this.#providerOptions.filterBackgroundAudio)
      );
    }
    if (this.#providerOptions.includeLanguageDetection !== undefined) {
      url.searchParams.set(
        "include_language_detection",
        String(this.#providerOptions.includeLanguageDetection)
      );
    }
    if (this.#providerOptions.enableLogging !== undefined) {
      url.searchParams.set(
        "enable_logging",
        String(this.#providerOptions.enableLogging)
      );
    }
    for (const keyterm of this.#providerOptions.keyterms ?? []) {
      url.searchParams.append("keyterms", keyterm);
    }
    return url.toString();
  }

  #sendAudioChunk(chunk: ArrayBuffer): void {
    try {
      this.#ws?.send(
        JSON.stringify({
          message_type: "input_audio_chunk",
          audio_base_64: arrayBufferToBase64(chunk),
          commit: false,
          sample_rate:
            this.#providerOptions.sampleRate ?? DEFAULT_STT_SAMPLE_RATE
        })
      );
    } catch (error) {
      if (!this.#closed) {
        console.error("[ElevenLabsSTT] WebSocket send failed:", error);
      }
    }
  }

  #handleMessage(event: MessageEvent): void {
    if (this.#closed || typeof event.data !== "string") return;

    let data: unknown;
    try {
      data = JSON.parse(event.data);
    } catch {
      return;
    }

    if (!isObject(data)) return;
    const messageType = data.message_type;
    if (messageType === "session_started") {
      this.#resolveReady();
      return;
    }

    if (messageType === "partial_transcript") {
      const text = stringProp(data, "text");
      if (text) {
        if (!this.#speechStarted) {
          this.#speechStarted = true;
          this.#sessionOptions?.onSpeechStart?.(text);
        }
        this.#sessionOptions?.onInterim?.(text);
      }
      return;
    }

    if (
      messageType === "committed_transcript" ||
      messageType === "committed_transcript_with_timestamps"
    ) {
      this.#speechStarted = false;
      const text = stringProp(data, "text");
      if (text) {
        this.#sessionOptions?.onUtterance?.(text);
      }
      return;
    }

    if (typeof messageType === "string" && messageType.includes("error")) {
      console.error(
        `[ElevenLabsSTT] ${messageType}: ${stringProp(data, "error") ?? event.data}`
      );
    }
  }
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function stringProp(
  value: Record<string, unknown>,
  key: string
): string | undefined {
  const prop = value[key];
  return typeof prop === "string" ? prop : undefined;
}

function arrayBufferToBase64(buffer: ArrayBuffer): string {
  const bytes = new Uint8Array(buffer);
  const chunkSize = 0x8000;
  let binary = "";
  for (let i = 0; i < bytes.length; i += chunkSize) {
    const chunk = bytes.subarray(i, i + chunkSize);
    binary += String.fromCharCode(...chunk);
  }
  return btoa(binary);
}
