/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 3e11e492aff9799a3f3d8b90d67e2d97)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  AI: Ai;
  SandboxAgent: DurableObjectNamespace<import("./src/server").SandboxAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "SandboxAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
