/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: b5a1a52b1a906461d0ee8841e45083ec)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  AI: Ai;
  Codemode: DurableObjectNamespace<import("./src/server").Codemode>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Codemode";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
