/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 22b18fabda87ed46fe2b66642dc982d5)
interface __BaseEnv_Env {
  TicTacToe: DurableObjectNamespace<import("./src/server").TicTacToe>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "TicTacToe";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
