/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 00a275119eb86dd225016cd9e2024099)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  AI: Ai;
  WorkerPlayground: DurableObjectNamespace<
    import("./src/server").WorkerPlayground
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "WorkerPlayground";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
