import { callable, routeAgentRequest } from "agents";
import { Think } from "@cloudflare/think";
import { createExecuteTool } from "@cloudflare/think/tools/execute";
import {
  BrowserConnector,
  DurableBrowserSessionStore,
  type BrowserLiveView
} from "agents/browser";
import type { ToolSet } from "ai";

// The execute tool runs sandboxed code on a durable codemode runtime that
// lives in a facet of the agent's Durable Object. That facet class must be
// exported from the Worker entry (the `agents:vite` plugin does not auto-wire
// it for the plain `src/server.ts` entry).
export { CodemodeRuntime } from "agents/browser";

// `Env` is the ambient interface generated by `wrangler types` into env.d.ts
// (AI, BROWSER, LOADER, LiveViewAgent). Regenerate it with `pnpm run types`.

// One shared browser session per agent, so a page the model opens stays open
// between turns — the human can act in the Live View while the run is idle,
// and the next turn continues against the same tabs and cookies.
const BROWSER_SESSION_KEY = "main";

export class LiveViewAgent extends Think<Env> {
  getModel() {
    return "@cf/moonshotai/kimi-k2.7-code";
  }

  getSystemPrompt() {
    return [
      "You drive a real Chrome browser with the `execute` tool, which runs TypeScript against a `cdp` connector (the Chrome DevTools Protocol).",
      "",
      "REUSE ONE TAB. The session persists across turns and already has a tab open, so do NOT open a new tab for every step — that piles up tabs. First list the open tabs with cdp.send({ method: 'Target.getTargets' }) and pick the existing page target (type 'page'). Attach to it — const { sessionId } = await cdp.attachToTarget({ targetId }) — and navigate it in place with cdp.send({ method: 'Page.navigate', params: { url }, sessionId }). Pass that sessionId to every page-scoped Page.*, Runtime.*, and DOM.* command.",
      "Only open a new tab with cdp.send({ method: 'Target.createTarget', params: { url } }) when you genuinely need a SECOND page open at the same time (e.g. comparing two pages). When you finish with an extra tab, close it with cdp.send({ method: 'Target.closeTarget', params: { targetId } }).",
      "Because the session persists, a page you navigate stays open for the next message.",
      "",
      "HUMAN HANDOFF (Live View): when a step needs a human — logging in, solving a CAPTCHA, multi-factor auth, or entering sensitive data — do NOT try to do it yourself. Instead:",
      "  1. Open/navigate to the page that needs the human.",
      "  2. Call cdp.getLiveViewUrl() to get a link the user can open to control the browser live.",
      "  3. Tell the user to open the Live Browser panel (or the link), complete the step, and reply when they are done.",
      "  4. After they confirm, continue — read cookies, the DOM, or navigate onward in the same session.",
      "",
      "Keep replies short. When you capture page text or data, summarize it rather than dumping everything."
    ].join("\n");
  }

  getTools(): ToolSet {
    return {
      // `cdp.*` (incl. cdp.getLiveViewUrl) comes from env.BROWSER; the executor
      // comes from env.LOADER. `reuse` keeps one shared session across turns.
      execute: createExecuteTool(this, {
        session: { mode: "reuse", key: BROWSER_SESSION_KEY }
      })
    };
  }

  #browser(): BrowserConnector {
    return new BrowserConnector(this.ctx, {
      browser: this.env.BROWSER,
      store: new DurableBrowserSessionStore(this.ctx.storage),
      session: { mode: "reuse", key: BROWSER_SESSION_KEY }
    });
  }

  /** Live View URLs for the shared browser session's open tabs, or null. */
  @callable()
  async liveView(): Promise<BrowserLiveView | null> {
    return (await this.#browser().liveView({ mode: "tab" })) ?? null;
  }

  /** Close the shared browser session, discarding its tabs and login state. */
  @callable()
  async closeBrowser(): Promise<void> {
    await this.#browser().closeSession();
  }
}

export default {
  async fetch(request: Request, env: Env) {
    return (
      (await routeAgentRequest(request, env)) ||
      new Response("Not found", { status: 404 })
    );
  }
} satisfies ExportedHandler<Env>;
