/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 53ed78ed90f5bb9426f10dfcc88600de)
interface __BaseEnv_Env {
  AI_GATEWAY_ACCOUNT_ID: "85d0c02b57ed75faf9b18f92d5c01602";
  AI_GATEWAY_ID: "anthropic-agent-patterns";
  OPENAI_API_KEY: string;
  AI_GATEWAY_TOKEN: string;
  sequential: DurableObjectNamespace<import("./src/server").Sequential>;
  routing: DurableObjectNamespace<import("./src/server").Routing>;
  parallel: DurableObjectNamespace<import("./src/server").Parallel>;
  orchestrator: DurableObjectNamespace<import("./src/server").Orchestrator>;
  evaluator: DurableObjectNamespace<import("./src/server").Evaluator>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces:
      | "Sequential"
      | "Routing"
      | "Parallel"
      | "Orchestrator"
      | "Evaluator";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "AI_GATEWAY_ACCOUNT_ID"
      | "AI_GATEWAY_ID"
      | "OPENAI_API_KEY"
      | "AI_GATEWAY_TOKEN"
    >
  > {}
}
