/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: b8c94f741dbb9f5874972dd5e50c0087)
interface __BaseEnv_Env {
  AUDIO_BUCKET: R2Bucket;
  AI: Ai;
  ELEVENLABS_API_KEY: string;
  VoiceChatAgent: DurableObjectNamespace<import("./src/server").VoiceChatAgent>;
  SoundscapeAgent: DurableObjectNamespace<
    import("./src/server").SoundscapeAgent
  >;
  CharacterAgent: DurableObjectNamespace<import("./src/server").CharacterAgent>;
  MusicAgent: DurableObjectNamespace<import("./src/server").MusicAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces:
      | "VoiceChatAgent"
      | "SoundscapeAgent"
      | "CharacterAgent"
      | "MusicAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "ELEVENLABS_API_KEY">
  > {}
}
