/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 5fbc0a448de36260d5d628b1955e46e6)
interface __BaseEnv_Env {
  DOCS_KV: KVNamespace;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server/index");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
