/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 70a93f67750cfddfd0b56fa2c023e65b)
interface __BaseEnv_Env {
  AI: Ai;
  MultiSessionAgent: DurableObjectNamespace<
    import("./src/server").MultiSessionAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MultiSessionAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
