/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 14aec921254f802e77a0468a6ebf98b6)
interface __BaseEnv_Env {
  AI: Ai;
  TaskAgent: DurableObjectNamespace<import("./src/server").TaskAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "TaskAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
